### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by greg0ire** [kinbiko/dotfiles#17]
Hi! I'm trying to convert my own config to Lua today, and I wanted to thank you for writing https://kinbiko.com/posts/2021-08-23-rewriting-vimrc-in-lua/ , it helped a lot.

I also came across https://icyphox.sh/blog/nvim-lua/, which has tips you might be interested in:

`local map = vim.api.nvim_set_keymap` could replace the custom function in `mappings.lua`
`local o = vim.o` could also help in `globals.lua`

I also found that it's important to reevaluate existing options, if you come from vim. For instance I dropped `vim.o.wildmenu = true`, because it's better in Neovim than it was in vim when I added that option.

Have a good day!

**Comment by kinbiko** [comment]
Thanks for the tips @greg0ire -- I'll apply your `local map` and `local o` tweaks. That `map` function used to assume `{noremap = true, silent = true}`, but no longer does, so the 
I'll remove the `wildmenu` option too. BTW: The reason the default is a lot better in Neovim is because `wildmenu` is enabled by default. 😄
